# Generated by Django 4.0.2 on 2022-02-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_savedcarts'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciones',
            name='category_description',
            field=models.TextField(default='descripcion manjus'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.TextField(default='descripcion'),
        ),
        migrations.AlterField(
            model_name='savedcarts',
            name='cart',
            field=models.TextField(default='descripcion'),
        ),
    ]
