# Generated by Django 4.0.2 on 2022-02-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_savedcarts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_png',
            new_name='category_gif',
        ),
        migrations.RenameField(
            model_name='manjus',
            old_name='dish_name',
            new_name='Sabor',
        ),
        migrations.RenameField(
            model_name='manjus',
            old_name='large_price',
            new_name='cajita',
        ),
        migrations.RenameField(
            model_name='manjus',
            old_name='small_price',
            new_name='individual',
        ),
        migrations.AddField(
            model_name='manjus',
            name='category_description',
            field=models.TextField(default='descripcion manjus'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.TextField(default='descripcion'),
        ),
        migrations.AlterField(
            model_name='savedcarts',
            name='cart',
            field=models.TextField(default='descripcion'),
        ),
    ]
