# Generated by Django 4.0.2 on 2022-02-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_category_png_category_category_gif_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_gif',
            new_name='category_png',
        ),
        migrations.RenameField(
            model_name='manjus',
            old_name='Sabor',
            new_name='sabor',
        ),
    ]
